ALTER TABLE "quizAttempts" ADD COLUMN "totalQuestions" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "quizAttempts" ADD COLUMN "pointsEarned" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "quizAttempts" ADD COLUMN "medal" text DEFAULT 'none' NOT NULL;--> statement-breakpoint
CREATE TABLE "userQuizStats" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "userQuizStats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"organization_id" text NOT NULL,
	"totalPoints" integer DEFAULT 0 NOT NULL,
	"bestScore" integer DEFAULT 0 NOT NULL,
	"bestTotalQuestions" integer DEFAULT 0 NOT NULL,
	"currentStreak" integer DEFAULT 0 NOT NULL,
	"bestStreak" integer DEFAULT 0 NOT NULL,
	"realAttemptsCount" integer DEFAULT 0 NOT NULL,
	"revisionAttemptsCount" integer DEFAULT 0 NOT NULL,
	"lastRealAttemptAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "userQuizStats" ADD CONSTRAINT "userQuizStats_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "userQuizStats" ADD CONSTRAINT "userQuizStats_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "user_quiz_stats_user_org_unique" ON "userQuizStats" USING btree ("userId","organization_id");--> statement-breakpoint
CREATE INDEX "user_quiz_stats_organization_idx" ON "userQuizStats" USING btree ("organization_id");
